<template>
  <EditorialPageShell wide>
    <div class="magazine-topline"><span>{{ siteStore.siteTitle || 'INKFLOW' }}</span><span>PERSONAL KNOWLEDGE JOURNAL</span><span>{{ today }}</span></div>
    <section class="magazine-intro"><p class="magazine-overline">A QUIET PLACE FOR LOUD IDEAS</p><h1>记录技术，也记录<br /><em>正在发生的生活。</em></h1><p class="magazine-deck">从代码、产品到日常思考，按自己的节奏阅读和写作。</p></section>
    <section v-if="articles.length" class="magazine-featured"><EditorialArticleCard :article="articles[0]" mode="featured" number="01" /><div class="magazine-featured-side"><EditorialArticleCard v-for="(article,index) in articles.slice(1,3)" :key="article.id" :article="article" mode="editorial" :number="`0${index+2}`" /></div></section>
    <div class="magazine-columns"><main><EditorialSectionHeader index="02" eyebrow="LATEST NOTES" title="最新文章" description="按时间顺序，浏览最近写下的内容。" /><div class="magazine-list"><EditorialArticleCard v-for="(article,index) in articles.slice(3)" :key="article.id" :article="article" mode="editorial" :number="String(index+4).padStart(2,'0')" /></div></main><aside><div class="magazine-aside-block"><EditorialSectionHeader index="03" eyebrow="THE EDITOR" title="关于这里" /><p>这里是一个不赶热点的个人博客。写下实践，也保留一些未完成的想法。</p><router-link to="/about" class="magazine-text-link">阅读关于页面 <span>↗</span></router-link></div><div class="magazine-aside-block"><EditorialSectionHeader index="04" eyebrow="RECENTLY" title="最近发布" /><EditorialArticleCard v-for="(article,index) in articles.slice(0,5)" :key="`recent-${article.id}`" :article="article" mode="compact" :number="String(index+1).padStart(2,'0')" /></div></aside></div>
  </EditorialPageShell>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue';
import EditorialPageShell from '../components/EditorialPageShell.vue';
import EditorialSectionHeader from '../components/EditorialSectionHeader.vue';
import EditorialArticleCard from '../components/EditorialArticleCard.vue';
import { getArticles } from '../api/article';
import { useSiteStore } from '../stores/site';
const siteStore=useSiteStore(); const articles=ref([]); const today=computed(()=>new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}));
onMounted(async()=>{ try { const res=await getArticles({page:1,size:12}); articles.value=res.data?.records||[]; } catch { articles.value=[]; } });
</script>
<style scoped>
.magazine-topline{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid var(--color-border);padding-bottom:12px;color:var(--color-text-soft);font:10px var(--font-mono);letter-spacing:.08em;text-transform:uppercase}.magazine-intro{padding:clamp(48px,9vw,120px) 0 clamp(38px,6vw,76px);border-bottom:1px solid var(--color-border)}.magazine-overline{margin:0 0 18px;color:var(--color-accent);font:11px var(--font-mono);letter-spacing:.16em}.magazine-intro h1{margin:0;color:var(--color-text);font-size:clamp(44px,8vw,104px);line-height:.94;letter-spacing:-.075em;font-weight:700}.magazine-intro h1 em{color:var(--color-text-muted);font-style:normal}.magazine-deck{max-width:440px;margin:28px 0 0;color:var(--color-text-muted);font-size:16px}.magazine-featured{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.75fr);gap:36px;padding:42px 0 72px}.magazine-featured-side{display:flex;flex-direction:column}.magazine-columns{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:72px}.magazine-aside-block{padding-bottom:34px}.magazine-aside-block p{margin:0 0 20px;color:var(--color-text-muted);font-size:14px;line-height:1.8}.magazine-text-link{color:var(--color-text);text-decoration:none;font:12px var(--font-mono);border-bottom:1px solid var(--color-accent);padding-bottom:4px}.magazine-list{display:flex;flex-direction:column}.magazine-list :deep(.editorial-card:first-child){border-top:0;padding-top:0}.magazine-aside-block :deep(.editorial-section-header){margin-bottom:10px}.magazine-aside-block :deep(.editorial-heading-row h2){font-size:28px}@media(max-width:900px){.magazine-featured,.magazine-columns{grid-template-columns:1fr;gap:40px}.magazine-featured-side{display:grid;grid-template-columns:1fr 1fr;gap:20px}.magazine-featured-side :deep(.editorial-card){display:block;border-top:0;padding:0}.magazine-columns aside{display:grid;grid-template-columns:1fr 1fr;gap:32px}}@media(max-width:600px){.magazine-topline span:nth-child(2){display:none}.magazine-intro h1{font-size:48px}.magazine-featured{padding-top:28px}.magazine-featured-side,.magazine-columns aside{display:block}.magazine-columns{gap:48px}}
</style>
