<template>
  <div class="admin-shell">
    <aside class="admin-sidebar" :class="{open: open}">
      <div class="admin-brand"><span class="admin-brand-mark">IF</span><span>工作台</span><button class="admin-close" @click="open=false">×</button></div>
      <nav v-for="group in groups" :key="group.label" class="admin-nav-group"><p>{{ group.label }}</p><router-link v-for="item in group.items" :key="item.to" :to="item.to" @click="open=false">{{ item.label }}</router-link></nav>
      <div class="admin-quick-link"><router-link to="/admin/ai/eval" @click="open=false">AI 评测</router-link></div>
    </aside>
    <button v-if="open" class="admin-backdrop" aria-label="关闭侧栏" @click="open=false"></button>
    <section class="admin-workspace"><header class="admin-topbar"><button class="admin-menu" aria-label="打开管理菜单" @click="open=true">☰</button><div><span class="admin-context">INKFLOW / ADMIN</span><strong>{{ currentTitle }}</strong></div><div class="admin-top-actions"><slot name="actions" /></div></header><div class="admin-content"><slot /></div></section>
  </div>
</template>
<script setup>
import { computed, ref } from 'vue'; import { useRoute } from 'vue-router';
const route=useRoute(); const open=ref(false); const groups=[{label:'内容',items:[{label:'文章管理',to:'/admin'},{label:'文章审核',to:'/admin/articles/review'},{label:'评论管理',to:'/admin/comments'},{label:'内容举报',to:'/admin/content-reports'},{label:'内容保鲜',to:'/admin/freshness'}]},{label:'用户与社区',items:[{label:'用户管理',to:'/admin/users'},{label:'聊天管理',to:'/admin/chat/messages'},{label:'在线监控',to:'/admin/chat/online'},{label:'推送管理',to:'/admin/push'}]},{label:'数据与运营',items:[{label:'数据看板',to:'/admin/dashboard'},{label:'操作日志',to:'/admin/logs'},{label:'性能监控',to:'/admin/monitor'},{label:'周报归档',to:'/admin/reports/weekly'}]},{label:'AI 与系统',items:[{label:'AI 监控',to:'/admin/ai-dashboard'},{label:'模型管理',to:'/admin/ai/models'},{label:'知识库',to:'/admin/knowledge'},{label:'站点设置',to:'/admin/settings'},{label:'数据库备份',to:'/admin/backup'}]}];
const currentTitle=computed(()=>groups.flatMap(g=>g.items).find(i=>route.path===i.to)?.label||'管理概览');
</script>
<style scoped>
.admin-shell{display:flex;min-height:calc(100vh - var(--layout-main-pad-top));background:var(--color-page)}.admin-sidebar{position:fixed;z-index:1250;top:0;bottom:0;width:238px;padding:28px 18px;background:var(--color-surface);border-right:1px solid var(--color-border);overflow:auto}.admin-brand{display:flex;align-items:center;gap:10px;padding:0 10px 26px;font-weight:700;color:var(--color-text);font-size:16px}.admin-brand-mark{display:grid;place-items:center;width:30px;height:30px;background:var(--color-primary);color:#fff;border-radius:7px;font:700 11px var(--font-mono)}.admin-close{display:none;margin-left:auto;border:0;background:transparent;color:var(--color-text-muted);font-size:24px}.admin-nav-group{margin:0 0 22px}.admin-nav-group p{margin:0 10px 8px;color:var(--color-text-soft);font:600 10px var(--font-mono);letter-spacing:.12em;text-transform:uppercase}.admin-nav-group a{display:block;padding:9px 10px;border-radius:6px;color:var(--color-text-muted);font-size:13px;text-decoration:none;transition:background .2s,color .2s}.admin-nav-group a:hover,.admin-nav-group a.router-link-active{color:var(--color-primary);background:var(--color-primary-soft);font-weight:600}.admin-workspace{width:calc(100% - 238px);margin-left:238px}.admin-topbar{position:sticky;top:0;z-index:100;display:flex;align-items:center;gap:14px;min-height:76px;padding:0 clamp(20px,4vw,44px);background:color-mix(in srgb,var(--color-page) 92%,transparent);border-bottom:1px solid var(--color-border);backdrop-filter:blur(12px)}.admin-context{display:block;color:var(--color-text-soft);font:10px var(--font-mono);letter-spacing:.1em}.admin-topbar strong{display:block;margin-top:5px;color:var(--color-text);font-size:20px}.admin-top-actions{margin-left:auto}.admin-content{padding:clamp(22px,4vw,48px);max-width:1500px}.admin-menu{display:none}.admin-backdrop{display:none}@media(max-width:900px){.admin-sidebar{transform:translateX(-100%);transition:transform .25s}.admin-sidebar.open{transform:translateX(0)}.admin-close,.admin-menu{display:block}.admin-menu{border:0;background:transparent;color:var(--color-text);font-size:20px;padding:4px}.admin-workspace{width:100%;margin-left:0}.admin-backdrop{display:block;position:fixed;inset:0;z-index:1240;background:rgba(0,0,0,.35);border:0}}
 .admin-nav-group a.router-link-active{border-left:3px solid var(--color-primary);padding-left:7px;background:var(--color-primary-soft);color:var(--color-primary)}
.admin-nav-group a{transition:background var(--transition-smooth),color var(--transition-smooth),border-color var(--transition-smooth)}
.admin-quick-link{margin:0 0 18px}.admin-quick-link a{display:block;padding:9px 10px;border-radius:6px;color:var(--color-text-muted);font-size:13px;text-decoration:none}.admin-quick-link a:hover,.admin-quick-link a.router-link-active{color:var(--color-primary);background:var(--color-primary-soft);font-weight:600}
.admin-sidebar{top:var(--layout-navbar-bottom);bottom:0;z-index:var(--z-admin-sticky);height:auto}
.admin-topbar{top:var(--layout-navbar-bottom);z-index:calc(var(--z-admin-sticky) - 1)}
@media(max-width:900px){.admin-sidebar{top:var(--layout-navbar-bottom);z-index:var(--z-nav-menu)}.admin-backdrop{top:var(--layout-navbar-bottom);z-index:calc(var(--z-nav-menu) - 1)}}
</style>
