server:
  port: 8082

spring:
  application:
    name: blog-auth
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        fail-fast: false
        register-enabled: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        ip-delete-timeout: 30000

management:
  server:
    port: 9082
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
