package com.blog.ai.runtime.model;

public enum AgentErrorCode {
    AGENT_INVALID_REQUEST,
    AGENT_UNSUPPORTED_TASK,
    AGENT_TIMEOUT,
    AGENT_CANCELLED,
    AGENT_BUDGET_EXCEEDED,
    AGENT_TOOL_DENIED,
    AGENT_TOOL_INVALID_ARGUMENT,
    AGENT_SAFETY_BLOCKED,
    AGENT_MODEL_UNAVAILABLE,
    AGENT_EVENT_CURSOR_EXPIRED
}
