spring:
  cloud:
    inetutils:
      preferred-networks:
        - 172.18
    nacos:
      discovery:
        ip: 120.48.48.31
        port: 8081
        fail-fast: false

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: INFO
